version: "3"
services:
  root:
    image: node:20.11.0-slim
    environment:
      - HOME=/tmp
    volumes:
      - .:/app
      - .npmrc:/tmp/.npmrc
      - nx_cache_root:/app/.nx
    working_dir: /app
    command:
      - sh
      - -c
      - |
        apt-get update &&
        apt-get install -y sudo &&
        chown ${UID:-0}:${GID:-0} ./.nx &&
        sudo --preserve-env -u \#${UID:-0} -g \#${GID:-0} npm install &&
        sudo --preserve-env -u \#${UID:-0} -g \#${GID:-0} npm run serve
  frontend:
    image: node:20.11.0-slim
    volumes:
      - .:/app
      - .npmrc:/tmp/.npmrc
      - nx_cache_frontend:/app/.nx
    working_dir: /app
    environment:
      - HOME=/tmp
      - REACT_APP_BACKEND_URL=http://localhost:${BE_APP_PORT:-3000}
      - VITE_APP_BACKEND=http://localhost:${BE_APP_PORT:-3000}
      - FE_PORT=${FE_PORT:-4000}
    ports:
      - ${FE_PORT:-4000}:${FE_PORT:-4000}
    command:
      - sh
      - -c
      - |
        apt-get update
        apt-get install -y sudo
        npm run wait
        chown ${UID:-0}:${GID:-0} ./.nx
        npm run wait
        sudo --preserve-env -u \#${UID:-0} -g \#${GID:-0} npx nx serve frontend
  backend:
    image: node:20.11.0-slim
    environment:
      - HOME=/tmp
      - NODE_ENV=development
      - HOST=${DEV_HOST}
      - KAFKA_BROKER=kafka:9092
    volumes:
      - .:/app
      - nx_cache_backend:/app/.nx
    working_dir: /app
    ports:
      - ${BE_DBG_PORT:-9229}:9229
      - ${BE_APP_PORT:-3000}:3000
    command:
      - sh
      - -c
      - |
        apt-get update
        apt-get install -y procps sudo
        npx nx reset
        npm run wait
        chown ${UID:-0}:${GID:-0} ./.nx
        sudo --preserve-env -u \#${UID:-0} -g \#${GID:-0} npx nx serve backend
    extra_hosts:
      - "dockerhost:host-gateway"
  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  frontend-user:
    image: node:20.11.0-slim
    volumes:
      - .:/app
      - .npmrc:/tmp/.npmrc
      - nx_cache_frontend-user:/app/.nx
    working_dir: /app
    environment:
      - HOME=/tmp
      - REACT_APP_BACKEND_URL=http://localhost:${BE_APP_PORT:-3000}
      - VITE_APP_BACKEND=http://localhost:${BE_APP_PORT:-3000}
      - FE2_PORT=${FE2_PORT:-5000}
    ports:
      - ${FE2_PORT:-5000}:${FE2_PORT:-5000}
    command:
      - sh
      - -c
      - >
        apt-get update

        apt-get install -y sudo

        npm run wait

        chown ${UID:-0}:${GID:-0} ./.nx

        npm run wait

        sudo --preserve-env -u \#${UID:-0} -g \#${GID:-0} npx nx serve
        frontend-user
volumes:
  nx_cache_root: null
  nx_cache_frontend: null
  nx_cache_backend: null
  database_data: null
  nx_cache_frontend-user: null
