version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend
      args:
        - VITE_APP_BACKEND=${VITE_APP_BACKEND:-http://localhost:3000}
    ports:
      - "8080:80"
    environment:
      - VITE_APP_BACKEND=${VITE_APP_BACKEND:-http://localhost:3000}

    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      target: backend
      args:
        - app_version=${APP_VERSION:-1.0.0}
        - app_source_branch=${APP_SOURCE_BRANCH:-main}
        - app_source_commit=${APP_SOURCE_COMMIT:-unknown}
        - app_build_time=${APP_BUILD_TIME:-unknown}
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    restart: unless-stopped

volumes:
  pg_data:

