database:
  host: database
  port: 5432 # Optional
  #  database: postgres      # Optional
  username: postgres
  password: postgres

corsEnabled: true # Optional, default: false

authentication:
  secret: secret # Optional, default: secret
  algorithm: HS256 # Optional, default: HS256

uploadsDir: uploads # Optional, default: ./uploads

admin:
  email: admin@worksolutions.ru # Optional, default: process.env.ADMIN_EMAIL ?? "admin@worksolutions.ru"
  password: worksolutions # Optional, default: process.env.ADMIN_PASSWORD ?? "worksolutions"
