database:
  host: database
  port: 5432 # Optional
  username: postgres
  password: postgres

corsEnabled: true # Optional, default: false

authentication:
  secret: secret # Optional, default: secret
  algorithm: HS256 # Optional, default: HS256

uploadsDir: uploads # Optional, default: ./uploads
