database:
  host: database
  port: 5432 # Optional
  #  database: postgres      # Optional
  username: postgres
  password: postgres

corsEnabled: true # Optional, default: false

authentication:
  secret: secret # Optional, default: secret
