name: Build Docker Compose

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - ".dockerignore"
      - ".gitignore"
      - "LICENSE"
      - ".gihub /**"

jobs:
  docker-compose-build:

    if: github.event_name == 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: false

      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Build Docker Compose Services
        run: |
          docker-compose -f docker-compose.yaml build --no-cache
        continue-on-error: false

      - name: Start Docker Compose Services
        run: |
          docker-compose -f docker-compose.yaml up -d --remove-orphans
        continue-on-error: false

      - name: Verify Running Containers
        run: |
          docker ps
          docker-compose ps
          docker-compose logs
        continue-on-error: false


      - name: Stop and Remove Docker Containers
        if: always()
        run: |
          docker-compose down

