name: Build Docker Compose

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
      - ".dockerignore"
      - ".gitignore"
      - "LICENSE"
      - ".gihub /**"

jobs:
  docker-compose-build:

    if: github.event_name == 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Step 4: Build Docker Compose
      - name: Build Docker Compose Services
        run: |
          docker-compose -f docker-compose.yaml config  # Validate the configuration
          docker-compose -f docker-compose.yaml up -d --build --remove-orphans

      # Step 5: Verify containers are running
      - name: Verify Running Containers
        run: |
          docker ps
          docker-compose ps

      # Step 6: Clean up
      - name: Stop and Remove Docker Containers
        if: always()
        run: |
          docker-compose down

