name: Security Scan
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@v2

      - name: Dependency vulnerability check
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - run: npm install --legacy-peer-deps
      - run: npm audit --production --audit-level=high

      - name: Snyk security scan
        uses: snyk/actions/node@master
        with:
          command: monitor
          args: --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

